config/routes.rb
SERVEReport::Application.routes.draw do

  resources :servers

  devise_for :users

   root :to => 'welcome#index'

end

app/models/server.rb
class Server < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.paginate :page => params[:page], :per_page => 5

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render json: @server, status: :created, location: @server }
      else
        format.html { render action: "new" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
before_filter :authenticate_user! 
 def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SERVEReport</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">SERVEReport</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
                <li><%= link_to "Servers Added", servers_path  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
                <li class="dropdown pull-right">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                 <ul class="dropdown-menu">
                     ...
                 </ul>
                </li>
                <li>
                 <%if current_user%>
                  <%= link_to "Logout", destroy_user_session_path,:method => :delete, :class => "pull-right"%>
                 <%else%>
                  <%= link_to "Login", user_session_path, :class => "pull-right"%>
                 <% end %> 
                </li>
           
            </ul>
           
           
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; CK 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/servers/_form.html.erb
<%= form_for @server, :html => { :class => 'form-inline form-bordered form-condensed' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Server</legend>

    <div class="control-group">
      <%= f.label :server_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :server_name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :server_ip, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :server_ip, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :server_key, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :server_key, :class => 'text_area', :rows => 8 %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', servers_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/servers/edit.html.erb
<%= render :partial => 'form' %>

app/views/servers/index.html.erb
<h1>Servers</h1>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>  
      <th>ID</th>
      <th>Server name</th>
      <th>Server ip</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.id %></td>
        <td><%= link_to server.server_name, server_path(server) %></td>
        <td><%= link_to server.server_ip, server_path(server) %></td>
        <td><%= server.created_at.strftime("%d-%m-%Y") if server.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_server_path(server), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', server_path(server), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_server_path, :class => 'btn btn-primary' %>
<div class="pagination">
 <%= will_paginate @servers %>
</div>

app/views/servers/new.html.erb
<%= render :partial => 'form' %>

app/views/servers/show.html.erb
<h1>Server</h1>

<p>
  <b>Server name</b><br>
  <%= @server.server_name %>
</p>

<p>
  <b>Server ip</b><br>
  <%= @server.server_ip %>
</p>

<p>
  <b>Server key</b><br>
  <%= @server.server_key %>
</p>

<p>
  <b>Status</b><br>
  <%= @server.status %>
</p>

<div class="form-actions">
  <%= link_to 'Back', servers_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_server_path(@server), :class => 'btn' %>
  <%= link_to 'Delete', server_path(@server), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>